//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Template
//  @ File Name : Ship.java
//  @ Date : 2014-04-16
//  @ Author : 
//
//



package com.kt.home;


public class Ship extends Vehicle {
	protected int cost() {
		return 100 + getDistance();
	}
}
