//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Template
//  @ File Name : Truck.java
//  @ Date : 2014-04-16
//  @ Author : 
//
//



package com.kt.home;


public class Truck extends Vehicle {
	protected int cost() {
		return getDistance()*3;
	}
}
