//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Template
//  @ File Name : Vehicle.java
//  @ Date : 2014-04-16
//  @ Author : 
//
//



package com.kt.home;


public abstract class Vehicle {
	private String start;
	private String dest;
	private int distance;
	protected abstract int cost();
	public String getStart() {
		return start;
	}
	public void setStart(String start) {
		this.start = start;
	}
	public String getDest() {
		return dest;
	}
	public void setDest(String dest) {
		this.dest = dest;
	}
	public int getDistance() {
		return distance;
	}
	public void setDistance(int distance) {
		this.distance = distance;
	}
	
}
