//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Template
//  @ File Name : VehicleUI.java
//  @ Date : 2014-04-16
//  @ Author : 
//
//



package com.kt.home;


public class VehicleUI {
	public VehicleController controller;
}
