//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Template
//  @ File Name : VehicleService.java
//  @ Date : 2014-04-16
//  @ Author : 
//
//



package com.kt.home;

//@Service
public class VehicleService {
//	public Vehicle vehicle;
	public int getCost(Vehicle v) {
		return v.cost();
	}
}
