//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Template
//  @ File Name : VehicleController.java
//  @ Date : 2014-04-16
//  @ Author : 
//
//



package com.kt.home;

//@Controller
public class VehicleController {
	
//	@Resource
	public VehicleService vehicleService;// = new VehicleService();
	public int printAirplaneCost() {
		Airplane v = new Airplane();
		v.setDistance(100);
		return vehicleService.getCost(v);
	}
	
	public int printTruckCost() {
		Truck v = new Truck();
		v.setDistance(300);
		return vehicleService.getCost(v);
	}
	
	public int printShipCost() {
		Ship v = new Ship();
		v.setDistance(200);
		return vehicleService.getCost(v);
	}
}
